### ISSUE TITLE
Query for create table causes error if table already exists in Cassandra 2.2

### ISSUE THREAD

**Issue by ivanquirino** [asafyish/connect-cassandra-cql#5]
Please consider changing the query to "CREATE TABLE IF NOT EXISTS..."

**Comment by asafyish** [comment]
Does "IF NOT EXISTS" works on cassandra 2.1 ?

**Comment by ivanquirino** [comment]
Yes it does. I Just checked http://docs.datastax.com/en/cql/3.1/cql/cql_reference/create_table_r.html for reference.

**Comment by ivanquirino** [comment]
Thank you. When there will be a new release on npm? Need to merge back from upstream.

**Comment by asafyish** [comment]
Already on npm.

**Comment by ivanquirino** [comment]
Thank you very much.
